import { getQuery } from "@/lib/query";
import { getCEP } from "@/lib/utils";
import axios from "axios";
import { type NextRequest, NextResponse } from "next/server";

const sedes = [
	{
		nome: "AERA Esportes Radicais",
		cep: "61700-000",
		rua: "A. Beira Mar, s/n Prainha",
		numero: "S/N",
		complemento: null,
	},
	{
		nome: "Alimentarize",
		cep: null,
		rua: null,
		numero: null,
		complemento: null,
	},
	{
		nome: "APDCAI",
		cep: "42800-745",
		rua: "Rua novo horizonte",
		numero: "100",
		complemento: null,
	},
	{
		nome: "Caverna de Adulão",
		cep: "61880-000",
		rua: "Av Deputado Paulino Rocha, Jabuti",
		numero: "2141",
		complemento: null,
	},
	{
		nome: "Conselho Comunitário do Parque São José CCPSJ",
		cep: "60730-255",
		rua: "Rua Costa Freire, Parque Sao Jose",
		numero: "2238",
		complemento: null,
	},
	{
		nome: "Doroteias - Arquitetura",
		cep: "60861-212",
		rua: "Avenida Alberto Craveiro",
		numero: "2222",
		complemento: null,
	},
	{
		nome: "FECARCE",
		cep: "60135-222",
		rua: "Rua Marcondes Pereira",
		numero: "1271",
		complemento: "Lj 03",
	},
	{
		nome: "Instituto Benjamim Dias",
		cep: "60521-075",
		rua: "Rua Eurico Medina, Henrique Jorge",
		numero: "1260",
		complemento: null,
	},
	{
		nome: "Instituto Lucimário Caitano",
		cep: "61919-600",
		rua: "Avenida central",
		numero: "120",
		complemento: null,
	},
	{
		nome: "Instituto Maria do Carmo",
		cep: "60540-830",
		rua: "ARua Coronel Fabriciano",
		numero: "1820",
		complemento: "Academia Sara",
	},
	{
		nome: "Instituto Recomeçando",
		cep: "60745-670",
		rua: "A. Beira Mar, s/n Prainha",
		numero: "295",
		complemento: "Rua Q",
	},
	{
		nome: "Instituto Vida Videira",
		cep: "60833-275",
		rua: "Rua São João Del Rey",
		numero: "1764",
		complemento: null,
	},
	{
		nome: "Lar Beneficente Cisco de Luz",
		cep: "61600-060",
		rua: "Rua Tobias Correia",
		numero: "1404",
		complemento: null,
	},
	{
		nome: "Lar Francisco de Assis",
		cep: "60810-792",
		rua: "Av. Rogaciano Leite",
		numero: "1650",
		complemento: null,
	},
	{
		nome: "Mães da Resistência",
		cep: "60040-130",
		rua: "Rua Olívio Câmara",
		numero: "74",
		complemento: null,
	},
	{
		nome: "Saboaria Ecológica",
		cep: "61631-016",
		rua: "R. Felipe Fernandes Neto",
		numero: "505",
		complemento: null,
	},
	{
		nome: "Assoc. Centro de Arte e Cultura Canoa Mulher",
		cep: "62800-000",
		rua: "Rua Agapito dos Santos",
		numero: "462",
		complemento: null,
	},
	{
		nome: "Associação Menino Jesus",
		cep: null,
		rua: "Sitio lagoa do canto",
		numero: null,
		complemento: null,
	},
	{
		nome: "Friends of Fiji Foundation ",
		cep: null,
		rua: "Quênia",
		numero: null,
		complemento: null,
	},
	{
		nome: "Grupo Mulheres do Brasil - Empregabilidade",
		cep: "60810-195",
		rua: "Av. Chanceler Edson Queiroz",
		numero: "100",
		complemento: "Loja 04",
	},
	{
		nome: "Instituto Intervalo",
		cep: "60861-212",
		rua: "Avenida Alberto Craveiro",
		numero: "2222",
		complemento: null,
	},
	{
		nome: "Instituto Queira Bem",
		cep: "60410-162",
		rua: "Rua Antônio Fiúza ",
		numero: "358",
		complemento: "Casa 02",
	},
	{
		nome: "Projeto Comunitário Sorriso da Criança",
		cep: "60355-360",
		rua: "Rua Planalto",
		numero: "167",
		complemento: null,
	},
	{
		nome: "Conselho Comunitário da Taíba",
		cep: "62670-000",
		rua: "Antônio Marques",
		numero: "1",
		complemento: "Centro",
	},
	{
		nome: "Rede Estrela de Iracema",
		cep: "60440-140",
		rua: "Rua Nogueira Acioly",
		numero: "1490",
		complemento: null,
	},
];

const oscs = [
	{
		nome: "AERA Esportes Radicais",
		zipCode: "61700-000",
		street: "",
		number: "S/N",
		complement: null,
		neighborhood: "",
		city: "Aquiraz",
		state: "CE",
	},
	{
		nome: "Alimentarize",
		zipCode: null,
		street: null,
		number: null,
		complement: null,
	},
	{
		nome: "APDCAI",
		zipCode: "42800-745",
		street: "Rua Novo Horizonte",
		number: "100",
		complement: null,
		neighborhood: "Jardim Limoeiro",
		city: "Camaçari",
		state: "BA",
	},
	{
		nome: "Caverna de Adulão",
		zipCode: "61880-000",
		street: "Av Deputado Paulino Rocha, Jabuti",
		number: "2141",
		complement: null,
	},
	{
		nome: "Conselho Comunitário do Parque São José CCPSJ",
		zipCode: "60730-255",
		street: "Rua Costa Freire",
		number: "2238",
		complement: null,
		neighborhood: "Parque São José",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Espaço Cultura e Vida Dorotéias",
		zipCode: "60861-212",
		street: "Avenida Alberto Craveiro",
		number: "2222",
		complement: null,
		neighborhood: "Boa Vista-Castelão",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "FECARCE",
		zipCode: "60135-222",
		street: "Rua Marcondes Pereira",
		number: "1271",
		complement: "Lj 03",
		neighborhood: "Dionisio Torres",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Instituto Benjamim Dias",
		zipCode: "60521-075",
		street: "Rua Eurico Medina",
		number: "1260",
		complement: null,
		neighborhood: "Henrique Jorge",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Instituto Lucimário Caitano",
		zipCode: "61919-600",
		street: "Avenida Central",
		number: "120",
		complement: null,
		neighborhood: "Novo Oriente",
		city: "Maracanaú",
		state: "CE",
	},
	{
		nome: "Instituto Maria do Carmo",
		zipCode: "60540-830",
		street: "ARua Coronel Fabriciano",
		number: "1820",
		complement: "Academia Sara",
	},
	{
		nome: "Instituto Recomeçando",
		zipCode: "60745-670",
		street: "Rua Q",
		number: "295",
		complement: "Rua Q",
		neighborhood: "Parque Dois Irmãos",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Instituto Vida Videira",
		zipCode: "60833-275",
		street: "Travessa Vitória Régia",
		number: "1764",
		complement: null,
		neighborhood: "Sapiranga-Coité",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Lar Beneficente Cisco de Luz",
		zipCode: "61600-060",
		street: "Rua Tobias Correia",
		number: "1404",
		complement: null,
		neighborhood: "Centro",
		city: "Caucaia",
		state: "CE",
	},
	{
		nome: "Lar Francisco de Assis",
		zipCode: "60810-792",
		street: "Avenida Rogaciano Leite",
		number: "1650",
		complement: null,
		neighborhood: "Salinas",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Mães da Resistência",
		zipCode: "60040-130",
		street: "Rua Olívio Câmara",
		number: "74",
		complement: null,
		neighborhood: "José Bonifácio",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Saboaria Ecológica",
		zipCode: "61631-016",
		street: "Rua Felipe Fernandes Neto",
		number: "505",
		complement: null,
		neighborhood: "Parque Leblon",
		city: "Caucaia",
		state: "CE",
	},
	{
		nome: "Assoc. Centro de Arte e Cultura Canoa Mulher",
		zipCode: "62800-000",
		street: "",
		number: "462",
		complement: null,
		neighborhood: "",
		city: "Aracati",
		state: "CE",
	},
	{
		nome: "Associação Menino Jesus",
		zipCode: null,
		street: "Sitio lagoa do canto",
		number: null,
		complement: null,
	},
	{
		nome: "Friends of Fiji Foundation ",
		zipCode: null,
		street: "Quênia",
		number: null,
		complement: null,
	},
	{
		nome: "Grupo Mulheres do Brasil - Empregabilidade",
		zipCode: "60810-195",
		street: "Rua Desembargador Manuel Sales Andrade",
		number: "100",
		complement: "Loja 04",
		neighborhood: "Guararapes",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Instituto Intervalo",
		zipCode: "60861-212",
		street: "Avenida Alberto Craveiro",
		number: "2222",
		complement: null,
		neighborhood: "Boa Vista-Castelão",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Instituto Queira Bem",
		zipCode: "60410-162",
		street: "Rua Antônio Fiuza",
		number: "358",
		complement: "Casa 02",
		neighborhood: "Montese",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Projeto Comunitário Sorriso da Criança",
		zipCode: "60355-360",
		street: "Rua do Planalto",
		number: "167",
		complement: null,
		neighborhood: "Presidente Kennedy",
		city: "Fortaleza",
		state: "CE",
	},
	{
		nome: "Conselho Comunitário da Taíba",
		zipCode: "62670-000",
		street: "",
		number: "1",
		complement: "Centro",
		neighborhood: "",
		city: "São Gonçalo do Amarante",
		state: "CE",
	},
	{
		nome: "Rede Estrela de Iracema",
		zipCode: "60440-140",
		street: "Rua Pernambuco",
		number: "1490",
		complement: null,
		neighborhood: "Demócrito Rocha",
		city: "Fortaleza",
		state: "CE",
	},
];

export async function GET(req: NextRequest) {
	try {
		const results = [];
		// zipCode      String?
		// street       String?
		// number       String?
		// complement   String?
		// neighborhood String?
		// city         String?
		// state        String?
		for (const sede of sedes) {
			const cep = sede.cep;
			const data = await getCEP(cep ?? "");

			results.push({
				nome: sede.nome,
				zipCode: cep,
				street: data?.logradouro ?? sede.rua,
				number: sede.numero,
				complement: sede.complemento,
				neighborhood: data?.bairro,
				city: data?.localidade,
				state: data?.uf,
			});
		}

		// const results = oscs.map((osc, index) => ({
		// 	id: index + 1,
		// 	name: osc.nome,
		// 	osc: {
		// 		name: osc.nome,
		// 		address: {
		// 			zipCode: osc.zipCode,
		// 			street: osc.street,
		// 			number: osc.number,
		// 			complement: osc.complement,
		// 			neighborhood: osc.neighborhood,
		// 			city: osc.city,
		// 			state: osc.state,
		// 		},
		// 	},
		// 	students: [],
		// }));

		return NextResponse.json(results);
	} catch (error) {
		return NextResponse.json(
			{ msg: "Falha ao buscar usuários", error },
			{ status: 500 },
		);
	}
}
