export const courses = [
	{ id: 1, name: "Administração" },
	{ id: 2, name: "Análise e Desenvolvimento de Sistemas" },
	{ id: 3, name: "Arquitetura e Urbanismo" },
	{ id: 4, name: "Biomedicina" },
	{ id: 5, name: "Business Agility" },
	{ id: 6, name: "Ciência da Computação" },
	{ id: 7, name: "Ciência da Felicidade, Trabalho e Produtividade" },
	{ id: 8, name: "Ciências Contábeis" },
	{ id: 9, name: "Construção de Edifícios" },
	{ id: 10, name: "Cuidados Paliativos Multiprofissionais" },
	{ id: 11, name: "Design de Interiores" },
	{ id: 12, name: "Direito" },
	{ id: 13, name: "Direito" },
	{ id: 14, name: "Direito Sindical" },
	{ id: 15, name: "Enfermagem" },
	{ id: 16, name: "Engenharia Ambiental e Sanitária" },
	{ id: 17, name: "Engenharia Civil" },
	{ id: 18, name: "Engenharia de Produção" },
	{ id: 19, name: "Engenharia Elétrica" },
	{ id: 20, name: "Engenharia Mecânica" },
	{ id: 21, name: "Especialização em Licitações e Contratações Públicas" },
	{ id: 22, name: "Especialização em Psicodrama" },
	{ id: 23, name: "Especialização em Teoria Psicanalítica" },
	{ id: 24, name: "Fisioterapia" },
	{ id: 25, name: "Gerenciamento de Projetos e Processos" },
	{ id: 26, name: "Gestão da Tecnologia da Informação" },
	{ id: 27, name: "Gestão de Recursos Humanos" },
	{ id: 28, name: "Gestão Financeira" },
	{ id: 29, name: "Intervenções em Situações de Perdas e Luto" },
	{ id: 30, name: "Jogos Digitais" },
	{ id: 31, name: "Marketing" },
	{ id: 32, name: "Marketing (Tecnólogo)" },
	{ id: 33, name: "Nutrição" },
	{ id: 34, name: "Pedagogia" },
	{ id: 35, name: "Processos Gerenciais" },
	{ id: 36, name: "Psicologia" },
];
export const socialMediaPlatforms = [
	{ id: 1, name: "Facebook" },
	{ id: 2, name: "Instagram" },
	{ id: 3, name: "Twitter" },
	{ id: 4, name: "LinkedIn" },
	{ id: 5, name: "YouTube" },
	{ id: 6, name: "Pinterest" },
	{ id: 7, name: "Snapchat" },
	{ id: 8, name: "TikTok" },
	{ id: 9, name: "Reddit" },
	{ id: 10, name: "Tumblr" },
];
export const projects = [
	{
		id: 1,
		name: "Instituto Vida Videira",
		osc: {
			name: "Instituto Vida Videira",
		},
		students: [
			{ name: "Paulo" },
			{ name: "Joelson" },
			{ name: "Alfredo" },
			{ name: "Washington" },
			{ name: "Larisson" },
		],
	},
	{
		id: 2,
		name: "FECARCE",
		osc: {
			name: "FECARCE",
		},
		students: [
			{ name: "Bruno Barroso de Castro" },
			{ name: "Derek Pinheiro Coelho Batista" },
			{ name: "Joao Vitor Sousa" },
			{ name: "Mateus Batista Gomes Sales" },
			{ name: "Matheus Vicente Benega" },
		],
	},
	{
		id: 3,
		name: "Instituto Maria do Carmo",
		osc: {
			name: "Instituto Maria do Carmo",
		},
		students: [
			{ name: "Abner Melo" },
			{ name: "Derek" },
			{ name: "Eduardo Garcia" },
			{ name: "Gleysse Ribeiro" },
			{ name: "Pedro Klein" },
		],
	},
	{
		id: 4,
		name: "Conselho Comunitário do Parque São José- CCPSJ",
		osc: {
			name: "CCPSJ",
		},
		students: [
			{ name: "Beatriz" },
			{ name: "Ana Luisa" },
			{ name: "Venício" },
			{ name: "Isabela" },
			{ name: "Lucas Rocha" },
		],
	},
	{
		id: 5,
		name: "Mães da Resistência",
		osc: {
			name: "Mães da Resistência",
		},
		students: [
			{ name: "Paulo Guilherme" },
			{ name: "Alice Oliveira" },
			{ name: "Acelino Marcos" },
			{ name: "Edberto Junior" },
			{ name: "Záfia Campelo" },
		],
	},
	{
		id: 6,
		name: "Instituto Recomeçando",
		osc: {
			name: "Instituto Recomeçando",
		},
		students: [
			{ name: "Amanda Morais" },
			{ name: "Maria Izabel" },
			{ name: "Amanda Deise" },
			{ name: "Raquel Holanda" },
			{ name: "Abraão Andrade" },
			{ name: "Elifas" },
		],
	},
	{
		id: 7,
		name: "Saboaria Ecológica",
		osc: {
			name: "Saboaria Ecológica",
		},
		students: [
			{ name: "Germana Salmito" },
			{ name: "Maria Ledio" },
			{ name: "Ludmilla" },
			{ name: "Érika" },
			{ name: "Nilse" },
		],
	},
	{
		id: 8,
		name: "APDCAI",
		osc: {
			name: "APDCAI",
		},
		students: [
			{ name: "Raissa Medeiros" },
			{ name: "Loren Souza" },
			{ name: "Tiffany Alves" },
			{ name: "Marina Vitorino" },
			{ name: "Gabrielle Iris" },
		],
	},
	{
		id: 9,
		name: "Caverna de Adulão",
		osc: {
			name: "Caverna de Adulão",
		},
		students: [
			{ name: "Daniella Ribeiro" },
			{ name: "Larissa" },
			{ name: "Débora" },
			{ name: "Claudenir" },
			{ name: "Layane" },
		],
	},
	{
		id: 10,
		name: "Instituição Lucimario Caetano",
		osc: {
			name: "Instituição Lucimario Caetano",
		},
		students: [
			{ name: "Victoria Homci" },
			{ name: "Yan Amorim" },
			{ name: "Andressa Pierre" },
			{ name: "Eron" },
		],
	},
	{
		id: 11,
		name: "Lar Beneficente Cisco de Luz",
		osc: {
			name: "Lar Beneficente Cisco de Luz",
		},
		students: [
			{ name: "Francisco Wlissis" },
			{ name: "Lorena Brito" },
			{ name: "Mariana" },
			{ name: "Anderson Almeida" },
		],
	},
	{
		id: 12,
		name: "Lar Francisco de Assis",
		osc: {
			name: "Lar Francisco de Assis",
		},
		students: [
			{ name: "Mariana Lemos" },
			{ name: "Ana Paula Reis" },
			{ name: "Francisco Marcelo Lima" },
			{ name: "Juliana Cavalcante Oliveira" },
			{ name: "Ana Karoliny da Silva Coelho" },
			{ name: "Marlom Bastos" },
		],
	},
	{
		id: 13,
		name: "Instituto Benjamim Dias",
		osc: {
			name: "Instituto Benjamim Dias",
		},
		students: [
			{ name: "Fernando" },
			{ name: "João pedro" },
			{ name: "Débora" },
			{ name: "Vitória" },
			{ name: "Nicolli" },
			{ name: "Erica" },
		],
	},
	{
		id: 14,
		name: "Aera",
		osc: {
			name: "Aera",
		},
		students: [
			{ name: "Roberto Jucá" },
			{ name: "Ester Jorge" },
			{ name: "Jana" },
			{ name: "Ayla" },
			{ name: "Gabriel" },
			{ name: "Paulo" },
			{ name: "HIARA" },
		],
	},
	{
		id: 15,
		name: "Espaço Cultura e Vida Dorotéias",
		osc: {
			name: "Espaço Cultura e Vida Dorotéias",
		},
		students: [
			{ name: "Aurislany Nunes" },
			{ name: "Maria do Socorro Araújo" },
			{ name: "Gabriella Sandim" },
			{ name: "Carlota Fiuza" },
			{ name: "Zafia Campelo" },
		],
	},
	{
		id: 16,
		name: "Alimentarize",
		osc: {
			name: "Alimentarize",
		},
		students: [
			{ name: "Edson Gabriel" },
			{ name: "Gabriel Queiroz" },
			{ name: "Hugo Matos" },
			{ name: "Armando Farias" },
			{ name: "Davi Negreiros" },
			{ name: "Luciano Castro" },
		],
	},
	{
		id: 17,
		name: "Mulheres do Brasil",
		osc: {
			name: "Mulheres do Brasil",
		},
		students: [
			{ name: "Caio Carvalho Portela" },
			{ name: "Josué de Sousa Lopes" },
			{ name: "Levi Gleik Andrade de Sousa" },
			{ name: "TiAGO" },
		],
	},
];
export const users = [
	{
		id: 1,
		name: "Levi Gleik",
		email: "leviacedo1@gmail.com",
		approved: true,
	},
	{
		id: 2,
		name: "Josué Lopes",
		email: "cmastercode77@gmail.com",
		approved: true,
	},
];
export const semesters = [
	{ id: 1, name: "2021.1" },
	{ id: 2, name: "2021.2" },
	{ id: 3, name: "2022.1" },
	{ id: 4, name: "2022.2" },
	{ id: 5, name: "2023.1" },
	{ id: 6, name: "2023.2" },
	{ id: 7, name: "2024.1" },
	{ id: 8, name: "2024.2" },
	{ id: 9, name: "2025.1" },
	{ id: 10, name: "2025.2" },
	{ id: 11, name: "2026.1" },
	{ id: 12, name: "2026.2" },
	{ id: 13, name: "2027.1" },
	{ id: 14, name: "2027.2" },
	{ id: 15, name: "2028.1" },
	{ id: 16, name: "2028.2" },
	{ id: 17, name: "2029.1" },
	{ id: 18, name: "2029.2" },
	{ id: 19, name: "2030.1" },
	{ id: 20, name: "2030.2" },
	{ id: 21, name: "2031.1" },
	{ id: 22, name: "2031.2" },
	{ id: 23, name: "2032.1" },
	{ id: 24, name: "2032.2" },
	{ id: 25, name: "2033.1" },
	{ id: 26, name: "2033.2" },
	{ id: 27, name: "2034.1" },
	{ id: 28, name: "2034.2" },
];
