export const courses = [
	{ id: 1, name: "Administração" },
	{ id: 2, name: "Análise e Desenvolvimento de Sistemas" },
	{ id: 3, name: "Arquitetura e Urbanismo" },
	{ id: 4, name: "Biomedicina" },
	{ id: 5, name: "Business Agility" },
	{ id: 6, name: "Ciência da Computação" },
	{ id: 7, name: "Ciência da Felicidade, Trabalho e Produtividade" },
	{ id: 8, name: "Ciências Contábeis" },
	{ id: 9, name: "Construção de Edifícios" },
	{ id: 10, name: "Cuidados Paliativos Multiprofissionais" },
	{ id: 11, name: "Design de Interiores" },
	{ id: 12, name: "Direito" },
	{ id: 13, name: "Direito Sindical" },
	{ id: 14, name: "Enfermagem" },
	{ id: 15, name: "Engenharia Ambiental e Sanitária" },
	{ id: 16, name: "Engenharia Civil" },
	{ id: 17, name: "Engenharia de Produção" },
	{ id: 18, name: "Engenharia Elétrica" },
	{ id: 19, name: "Engenharia Mecânica" },
	{ id: 20, name: "Especialização em Licitações e Contratações Públicas" },
	{ id: 21, name: "Especialização em Psicodrama" },
	{ id: 22, name: "Especialização em Teoria Psicanalítica" },
	{ id: 23, name: "Fisioterapia" },
	{ id: 24, name: "Gerenciamento de Projetos e Processos" },
	{ id: 25, name: "Gestão da Tecnologia da Informação" },
	{ id: 26, name: "Gestão de Recursos Humanos" },
	{ id: 27, name: "Gestão Financeira" },
	{ id: 28, name: "Intervenções em Situações de Perdas e Luto" },
	{ id: 29, name: "Jogos Digitais" },
	{ id: 30, name: "Marketing" },
	{ id: 31, name: "Marketing (Tecnólogo)" },
	{ id: 32, name: "Nutrição" },
	{ id: 33, name: "Pedagogia" },
	{ id: 34, name: "Processos Gerenciais" },
	{ id: 35, name: "Psicologia" },
];
export const socialMediaPlatforms = [
	{ id: 1, name: "Facebook" },
	{ id: 2, name: "Instagram" },
	{ id: 3, name: "Twitter" },
	{ id: 4, name: "LinkedIn" },
	{ id: 5, name: "YouTube" },
	{ id: 6, name: "Pinterest" },
	{ id: 7, name: "Snapchat" },
	{ id: 8, name: "TikTok" },
	{ id: 9, name: "Reddit" },
	{ id: 10, name: "Tumblr" },
];
export const projects = [
	{
		id: 1,
		name: "Instituto Vida Videira",
		osc: {
			name: "Instituto Vida Videira",
		},
		students: [
			{ name: "PAULO DA SILVA AMORIM", whatsapp: "" },
			{ name: "JOELSON FREITAS DE OLIVEIRA", whatsapp: "+558597847257" },
			{ name: "ALFREDO ALVES DE MAGALHAES NETO", whatsapp: "+558591480603" },
			{ name: "WASHINGTON BATISTA SILVA", whatsapp: "+558588092350" },
			{ name: "LARISSON DOS SANTOS DE AQUINO", whatsapp: "+558584035278" },
		],
	},
	{
		id: 2,
		name: "FECARCE",
		osc: {
			name: "FECARCE",
		},
		students: [
			{ name: "Bruno Barroso de Castro", whatsapp: "+558596181311" },
			{ name: "Derek Pinheiro Coelho Batista", whatsapp: "+558597509730" },
			{ name: "JOAO VITOR SOUSA SILVA", whatsapp: "" },
			{ name: "Mateus Batista Gomes Sales", whatsapp: "+558597993956" },
			{ name: "Matheus Vicente Benega", whatsapp: "+558598138750" },
		],
	},
	{
		id: 3,
		name: "Instituto Maria do Carmo",
		osc: {
			name: "Instituto Maria do Carmo",
		},
		students: [
			{ name: "ABNER OLIVEIRA DE MELO", whatsapp: "" },
			{ name: "DEREK PINHEIRO COELHO BATISTA", whatsapp: "+558597509730" },
			{ name: "EDUARDO GARCIA LEITE DE ALMEIDA ARAUJO", whatsapp: "" },
			{ name: "GLEYSSE RIBEIRO DA COSTA", whatsapp: "" },
			{ name: "PEDRO KLEIN DA SILVA RIBEIRO", whatsapp: "" },
		],
	},
	{
		id: 4,
		name: "Conselho Comunitário do Parque São José- CCPSJ",
		osc: {
			name: "CCPSJ",
		},
		students: [
			{ name: "Beatriz", whatsapp: "+558599482717" },
			{ name: "Ana Luisa", whatsapp: "" },
			{ name: "Venício", whatsapp: "" },
			{ name: "Isabela", whatsapp: "+558592439981" },
			{ name: "Lucas Rocha", whatsapp: "" },
		],
	},
	{
		id: 5,
		name: "Mães da Resistência",
		osc: {
			name: "Mães da Resistência",
		},
		students: [
			{ name: "PAULO GUILHERME NOBRE", whatsapp: "" },
			{ name: "ALICE DOS SANTOS OLIVEIRA", whatsapp: "+558597752922" },
			{ name: "ACELINO MARCOS DIOGENES ALVES", whatsapp: "" },
			{ name: "Edberto Junior", whatsapp: "" },
			{ name: "ZAFIA LUIZA SILVERIO CAMPELO DA COSTA", whatsapp: "" },
		],
	},
	{
		id: 6,
		name: "Instituto Recomeçando",
		osc: {
			name: "Instituto Recomeçando",
		},
		students: [
			{ name: "AMANDA DE SOUSA MORAIS", whatsapp: "+558588738173" },
			{ name: "MARIA IZABEL CIDRAO CAVALCANTE MOTA", whatsapp: "" },
			{ name: "Amanda Deise", whatsapp: "+558588738173" },
			{ name: "RAQUEL GOMES DE HOLANDA PIRES", whatsapp: "+558597926902" },
			{ name: "Abraão Andrade", whatsapp: "" },
			{ name: "ELIFAS DA SILVA LEMOS", whatsapp: "" },
		],
	},
	{
		id: 7,
		name: "Saboaria Ecológica",
		osc: {
			name: "Saboaria Ecológica",
		},
		students: [
			{ name: "GERMANA ANDRADE SALMITO", whatsapp: "+558599948919" },
			{ name: "MARIA LEDIO VIEIRA", whatsapp: "+558599376857" },
			{ name: "LUDMILLA GARCIA LIMA", whatsapp: "" },
			{ name: "ERIKA JANAINA SILVA MARQUES ARAUJO", whatsapp: "+558597629513" },
			{ name: "NILCE GONÇALVES DIAS", whatsapp: "" },
		],
	},
	{
		id: 8,
		name: "APDCAI",
		osc: {
			name: "APDCAI",
		},
		students: [
			{ name: "RAISSA LEITE MEDEIROS", whatsapp: "" },
			{ name: "LOREN SOUSA FERREIRA DOS SANTOS", whatsapp: "" },
			{ name: "TIFANNY EMILY ALVES DOS SANTOS", whatsapp: "" },
			{ name: "Marina Vitorino", whatsapp: "+558597157400" },
			{ name: "GABRIELE IRIS ALVES PESSOA", whatsapp: "" },
		],
	},
	{
		id: 9,
		name: "Caverna de Adulão",
		osc: {
			name: "Caverna de Adulão",
		},
		students: [
			{ name: "DANIELLA RIBEIRO DA PAZ", whatsapp: "+558585457115" },
			{ name: "LARYSSA LEE SOUSA MARQUES", whatsapp: "" },
			{ name: "DEBORA DA SILVA PEREIRA", whatsapp: "+558591760584" },
			{ name: "CLAUDENIR DE AQUINO SOUZA", whatsapp: "+558599252464" },
			{ name: "LAYANNE CRUZ CASTELO", whatsapp: "" },
		],
	},
	{
		id: 10,
		name: "Instituição Lucimario Caetano",
		osc: {
			name: "Instituição Lucimario Caetano",
		},
		students: [
			{ name: "VICTORIA HOMCI SAMPAIO TAVARES", whatsapp: "+558588705029" },
			{ name: "Yan Amorim", whatsapp: "" },
			{ name: "Andressa Pierre", whatsapp: "+558591105853" },
			{ name: "ERON FERNANDES MEDEIROS", whatsapp: "+558581393708" },
		],
	},
	{
		id: 11,
		name: "Lar Beneficente Cisco de Luz",
		osc: {
			name: "Lar Beneficente Cisco de Luz",
		},
		students: [
			{ name: "FRANCISCO WLISSIS RIBEIRO DE SOUZA", whatsapp: "" },
			{ name: "LORENA ROCHA BRITO", whatsapp: "" },
			{ name: "MARIANA GONCALVES GULDEN GRAVATA", whatsapp: "" },
			{ name: "Anderson Almeida", whatsapp: "" },
		],
	},
	{
		id: 12,
		name: "Lar Francisco de Assis",
		osc: {
			name: "Lar Francisco de Assis",
		},
		students: [
			{ name: "Mariana Lemos", whatsapp: "" },
			{ name: "Ana Paula Reis", whatsapp: "" },
			{ name: "FRANCISCO MARCELO LIMA AGUIAR JUNIOR", whatsapp: "" },
			{ name: "Juliana Cavalcante Oliveira", whatsapp: "" },
			{ name: "Ana Karoliny da Silva Coelho", whatsapp: "" },
			{ name: "MARLON BASTOS PINHEIRO", whatsapp: "" },
		],
	},
	{
		id: 13,
		name: "Instituto Benjamim Dias",
		osc: {
			name: "Instituto Benjamim Dias",
		},
		students: [
			{ name: "Fernando", whatsapp: "" },
			{ name: "João pedro", whatsapp: "+55 85 8575-7801" },
			{ name: "Débora", whatsapp: "" },
			{ name: "Vitória", whatsapp: "" },
			{ name: "Nicolli", whatsapp: "" },
			{ name: "Erica", whatsapp: "" },
		],
	},
	{
		id: 14,
		name: "Aera",
		osc: {
			name: "Aera",
		},
		students: [
			{ name: "Roberto Jucá", whatsapp: "+558596414309" },
			{ name: "Ester Jorge", whatsapp: "+558596896101" },
			{ name: "Jana", whatsapp: "+558592589999" },
			{ name: "Ayla", whatsapp: "" },
			{ name: "Gabriel", whatsapp: "" },
			{ name: "Paulo", whatsapp: "" },
			{ name: "HIARA", whatsapp: "" },
		],
	},
	{
		id: 15,
		name: "Espaço Cultura e Vida Dorotéias",
		osc: {
			name: "Espaço Cultura e Vida Dorotéias",
		},
		students: [
			{ name: "Aurislany Nunes", whatsapp: "" },
			{ name: "Maria do Socorro Araújo", whatsapp: "" },
			{ name: "Gabriella Sandim", whatsapp: "+558599751955" },
			{ name: "Carlota Fiuza", whatsapp: "" },
			{ name: "Zafia Campelo", whatsapp: "" },
		],
	},
	{
		id: 16,
		name: "Alimentarize",
		osc: {
			name: "Alimentarize",
		},
		students: [
			{ name: "Edson Gabriel", whatsapp: "" },
			{ name: "Gabriel Queiroz", whatsapp: "" },
			{ name: "Hugo Matos", whatsapp: "" },
			{ name: "Armando Farias", whatsapp: "" },
			{ name: "Davi Negreiros", whatsapp: "+558596607722" },
			{ name: "Luciano Castro", whatsapp: "+558599866662" },
		],
	},
	{
		id: 17,
		name: "Mulheres do Brasil",
		osc: {
			name: "Mulheres do Brasil",
		},
		students: [
			{ name: "Caio Carvalho Portela", whatsapp: "+558596159985" },
			{ name: "Josué de Sousa Lopes", whatsapp: "+558585325761" },
			{ name: "Levi Gleik Andrade de Sousa", whatsapp: "+558591437740" },
		],
	},
];
export const users = [
	{
		id: 1,
		name: "Levi Gleik",
		email: "leviacedo1@gmail.com",
		approved: true,
	},
	{
		id: 2,
		name: "Josué Lopes",
		email: "cmastercode77@gmail.com",
		approved: true,
	},
	{
		id: 3,
		name: "Caio Portela",
		email: "ccarvalho451@gmail.com",
		approved: true,
	},
];
export const semesters = [
	{ id: 1, name: "2021.1" },
	{ id: 2, name: "2021.2" },
	{ id: 3, name: "2022.1" },
	{ id: 4, name: "2022.2" },
	{ id: 5, name: "2023.1" },
	{ id: 6, name: "2023.2" },
	{ id: 7, name: "2024.1" },
	{ id: 8, name: "2024.2" },
	{ id: 9, name: "2025.1" },
	{ id: 10, name: "2025.2" },
	{ id: 11, name: "2026.1" },
	{ id: 12, name: "2026.2" },
	{ id: 13, name: "2027.1" },
	{ id: 14, name: "2027.2" },
	{ id: 15, name: "2028.1" },
	{ id: 16, name: "2028.2" },
	{ id: 17, name: "2029.1" },
	{ id: 18, name: "2029.2" },
	{ id: 19, name: "2030.1" },
	{ id: 20, name: "2030.2" },
	{ id: 21, name: "2031.1" },
	{ id: 22, name: "2031.2" },
	{ id: 23, name: "2032.1" },
	{ id: 24, name: "2032.2" },
	{ id: 25, name: "2033.1" },
	{ id: 26, name: "2033.2" },
	{ id: 27, name: "2034.1" },
	{ id: 28, name: "2034.2" },
];
