export const courses = [
	{ id: 1, name: "Administração" },
	{ id: 2, name: "Análise e Desenvolvimento de Sistemas" },
	{ id: 3, name: "Arquitetura e Urbanismo" },
	{ id: 4, name: "Biomedicina" },
	{ id: 5, name: "Business Agility" },
	{ id: 6, name: "Ciência da Computação" },
	{ id: 7, name: "Ciência da Felicidade, Trabalho e Produtividade" },
	{ id: 8, name: "Ciências Contábeis" },
	{ id: 9, name: "Construção de Edifícios" },
	{ id: 10, name: "Cuidados Paliativos Multiprofissionais" },
	{ id: 11, name: "Design de Interiores" },
	{ id: 12, name: "Direito" },
	{ id: 13, name: "Direito Sindical" },
	{ id: 14, name: "Enfermagem" },
	{ id: 15, name: "Engenharia Ambiental e Sanitária" },
	{ id: 16, name: "Engenharia Civil" },
	{ id: 17, name: "Engenharia de Produção" },
	{ id: 18, name: "Engenharia Elétrica" },
	{ id: 19, name: "Engenharia Mecânica" },
	{ id: 20, name: "Especialização em Licitações e Contratações Públicas" },
	{ id: 21, name: "Especialização em Psicodrama" },
	{ id: 22, name: "Especialização em Teoria Psicanalítica" },
	{ id: 23, name: "Fisioterapia" },
	{ id: 24, name: "Gerenciamento de Projetos e Processos" },
	{ id: 25, name: "Gestão da Tecnologia da Informação" },
	{ id: 26, name: "Gestão de Recursos Humanos" },
	{ id: 27, name: "Gestão Financeira" },
	{ id: 28, name: "Intervenções em Situações de Perdas e Luto" },
	{ id: 29, name: "Jogos Digitais" },
	{ id: 30, name: "Marketing" },
	{ id: 31, name: "Marketing (Tecnólogo)" },
	{ id: 32, name: "Nutrição" },
	{ id: 33, name: "Pedagogia" },
	{ id: 34, name: "Processos Gerenciais" },
	{ id: 35, name: "Psicologia" },
];
